# A config https://github.com/cicirello/generate-sitemap

name: 'generate-sitemap'
description: 'Generate an XML sitemap for a GitHub Pages site using GitHub Actions'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  path-to-root:  
    description: 'The path to the root of the website'
    required: false
    default: '.'
  base-url-path:
    description: 'The url of your webpage'
    required: false
    default: 'https://hubgames.studio²/'
  include-html:
    description: 'Indicates whether to include html files in the sitemap.'
    required: false
    default: true
  include-pdf:
    description: 'Indicates whether to include pdf files in the sitemap.'
    required: false
    default: true
  sitemap-format:
    description: 'Indicates if sitemap should be formatted in xml.'
    required: false
    default: 'xml'
  additional-extensions:
    description: 'Space separated list of additional file extensions to include in sitemap.'
    required: false
    default: ''
  drop-html-extension:
    description: 'Enables dropping .html from urls in sitemap.'
    required: false
    default: false
  date-only:
    description: 'Pass true to include only the date without the time in XML sitemaps; and false to include full date and time.'
    required: false
    default: false
  exclude-paths:
    description: 'Space separated list of paths to exclude from the sitemap.'
    required: false
    default: ''
outputs:
  sitemap-path: 
    description: 'The path to the generated sitemap file.'
  url-count:
    description: 'The number of entries in the sitemap.'
  excluded-count:
    description: 'The number of html files excluded from sitemap due to noindex meta tag.' 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path-to-root }}
    - ${{ inputs.base-url-path }}
    - ${{ inputs.include-html }}
    - ${{ inputs.include-pdf }}
    - ${{ inputs.sitemap-format }}
    - ${{ inputs.additional-extensions }}
    - ${{ inputs.drop-html-extension }}
    - ${{ inputs.date-only }}
    - ${{ inputs.exclude-paths }}
